version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - '5672:5672'
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  db:
    container_name: gateway
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '3000:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local